server:
  port: 9000
  
spring:
  cloud:
    gateway:
      routes:
        #Route Mapping
      - id: jfs-ribbon-app             #RouteIdentifier
        uri: http://localhost:1111/         #Respective microservice URL which needs to be mapped
         #Request Context Path Mapping
        predicates:
        - Path=/prod/**  